theme: jekyll-theme-modernist

url: https://joewheaton-org.github.io

baseurl: "/etal"

port: 4001

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

settings:
  autoPageContents:
    active: true
    onHome: false
    
  sideMenu:
    homeItem: true
    startexpanded: true
